### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by 2263379849** [EricLiuCN/barcode#2]
我是学习java的新人，我想使用您的这个数据库资源，做一个超市管理系统。好像下载不了，您能把资源给吗？非常感谢

**Comment by EricLiuCN** [comment]
> 
> 
> 我是学习java的新人，我想使用您的这个数据库资源，做一个超市管理系统。好像下载不了，您能把资源给吗？非常感谢

**Comment by EricLiuCN** [comment]
> 
> 
> 我是学习java的新人，我想使用您的这个数据库资源，做一个超市管理系统。好像下载不了，您能把资源给吗？非常感谢

刚看了一下，下载应该是没有问题的。可能是因为网络原因造成
你可以去国内的Gitee上搜索下载。
