### ISSUE TITLE
没有价格

### ISSUE THREAD

**Issue by cheov** [EricLiuCN/barcode#3]
希望能添加价格

**Comment by tuhe32** [comment]
在哪能获得价格数据

**Comment by EricLiuCN** [comment]
> 
> 
> 在哪能获得价格数据

现在市面上大部分接口都是收费的，所以能找到的资源不多。之前偶然发现一个免费接口 [https://github.com/MZCretin/RollToolsApi](https://github.com/MZCretin/RollToolsApi#%E8%8E%B7%E5%8F%96%E6%9D%A1%E5%BD%A2%E7%A0%81%E5%AF%B9%E5%BA%94%E7%9A%84%E5%95%86%E5%93%81%E4%BF%A1%E6%81%AF) 带有价格信息，想爬一份数据共享。 但是最终是我的ip被封，接口也无法使用了。 希望对你们有用

**Comment by xiaobai987292** [comment]
https://www.mxnzp.com/api/barcode/goods/details?barcode=6934278802230&app_id=3iigdjgokhe9tmrq&app_secret=emVSN1FNamM1b1lEYjFrZFNNekxNUT09
